import { Inter } from "next/font/google";
import "./globals.css";
import { AppNavbar } from "@/components/navbar";
import { DragoProvider } from "./lib/context/dataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DragoProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppNavbar />
          {children}
        </body>
      </html>
    </DragoProvider>
  );
}
